name: norminette

on: [push]

jobs:
  build:

    runs on: ubuntu-latest

    steps:
      - uses:  actions/checkout@v2
      - name: pip
      uses: BSFishy/pip-action@v1
      with:
        packages: norminette
        upgrade: true
      -name: Check norm errors
        run: norminette ./src ./include