name: Norminette
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ pull_request ]
jobs:
  Norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pip
        uses: BSFishy/pip-action@v1
        with:
          packages: norminette
          upgrade: true
      - name: Check norm errors
        run: norminette ./src ./include